name: Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# ----------------------------- [Test (start)] ----------------------------
  test:       
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']

    steps:
    - name:
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
           cd backend
           touch .env
           echo "${{secrets.ALL_SECRETS}}" >> .env

    - name: Test printing your secret 
      run: |
           cd backend
           cat .env

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'


    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install Dependencies
      run: |
           cd backend
           npm install

    - name: Run tests
      run: |
           cd backend
           npm test
# ------------------------------ [TEST (end)] -----------------------------
